import { test, expect } from '@playwright/test';

test.use({
  ignoreHTTPSErrors: true
});

test('test', async ({ page }) => {
  await page.goto('https://103.38.50.149:5005/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('admin');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('textbox', { name: 'Password' }).press('Tab');
  await page.getByRole('checkbox', { name: 'Remember me' }).press('Tab');
  await page.getByRole('button', { name: 'Log In' }).press('Enter');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByText('Transport').click();
  await page.getByRole('button', { name: 'plus Add Transporter' }).click();
  await page.locator('div').filter({ hasText: 'Add TransporterTransporter' }).nth(4).press('Tab');
  await page.getByRole('button', { name: 'Close' }).press('Tab');
  await page.getByRole('textbox', { name: '* Transporter Name' }).fill('sample154');
  await page.getByRole('textbox', { name: '* Transporter Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Contact Person' }).fill('conanme');
  await page.getByRole('textbox', { name: 'Contact Person' }).press('Tab');
  await page.getByRole('textbox', { name: '* Phone Number' }).fill('2365147890');
  await page.getByRole('textbox', { name: '* Phone Number' }).press('Tab');
  await page.getByRole('button', { name: 'Cancel' }).press('Tab');
  await page.getByRole('button', { name: 'OK' }).press('Enter');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('cell', { name: 'View Details' }).first().click();
  await page.getByRole('textbox', { name: '* Branch Name' }).click();
  await page.getByRole('textbox', { name: '* Branch Name' }).fill('name');
  await page.getByRole('textbox', { name: 'Branch Phone' }).click();
  await page.getByRole('textbox', { name: 'Branch Phone' }).fill('num');
  await page.getByRole('textbox', { name: 'Branch Address' }).click();
  await page.getByRole('textbox', { name: 'Branch Address' }).fill('add');
  await page.getByRole('button', { name: 'plus Add Branch' }).click();
  await page.getByRole('textbox', { name: '* Branch Name' }).click();
  await page.getByRole('textbox', { name: '* Branch Name' }).fill('name1');
  await page.getByRole('textbox', { name: 'Branch Phone' }).click();
  await page.getByRole('textbox', { name: 'Branch Phone' }).fill('num321');
  await page.getByRole('textbox', { name: 'Branch Address' }).click();
  await page.getByRole('textbox', { name: 'Branch Address' }).fill('address2');
  await page.getByRole('button', { name: 'plus Add Branch' }).click();
  await page.locator('.ant-btn.css-mncuj7.ant-btn-text.ant-btn-dangerous').first().click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('Schemes', { exact: true }).click();
  await page.getByRole('button', { name: '+ New Scheme' }).click();
  await page.getByRole('textbox', { name: '* Scheme Name' }).click();
  await page.getByRole('textbox', { name: '* Scheme Name' }).fill('schemename');
  await page.getByRole('spinbutton', { name: '* Amount Per Month' }).click();
  await page.getByRole('spinbutton', { name: '* Amount Per Month' }).fill('36925');
  await page.getByRole('spinbutton', { name: '* Period (Months)' }).click();
  await page.getByRole('spinbutton', { name: '* Period (Months)' }).fill('10');
  await page.getByRole('spinbutton', { name: '* Period (Months)' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'Bonus Amount' }).fill('25639');
  await page.getByRole('spinbutton', { name: 'Bonus Amount' }).press('Tab');
  await page.getByRole('spinbutton', { name: '* Total Amount' }).press('Tab');
  await page.getByRole('spinbutton', { name: '* Number of Dues' }).press('Tab');
  await page.getByRole('textbox', { name: 'Start Month' }).fill('01-03-2026');
  await page.getByRole('textbox', { name: 'Start Month' }).press('Enter');
  await page.getByRole('textbox', { name: 'Start Month' }).press('Tab');
  await page.getByRole('textbox', { name: 'End Month' }).press('Tab');
  await page.getByRole('button', { name: 'Cancel' }).press('Tab');
  await page.getByRole('button', { name: 'OK' }).press('Enter');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'edit' }).first().click();
  await page.getByRole('spinbutton', { name: 'Bonus Amount' }).click();
  await page.getByRole('spinbutton', { name: 'Bonus Amount' }).fill('25638');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Customers').click();
  await page.getByRole('button', { name: 'plus Add Customer' }).click();
  await page.getByRole('textbox', { name: '* Customer Code' }).click();
  await page.getByRole('textbox', { name: '* Customer Code' }).fill('SAM256');
  await page.getByRole('textbox', { name: 'Name', exact: true }).click();
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('KOMu');
  await page.getByRole('textbox', { name: 'Name', exact: true }).press('Tab');
  await page.getByRole('spinbutton', { name: '* Phone number' }).fill('9486540461');
  await page.getByRole('spinbutton', { name: '* Phone number' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'Secondary Phone' }).press('Tab');
  await page.getByRole('combobox', { name: 'Customer Type' }).press('Enter');
  await page.getByRole('combobox', { name: 'Customer Type' }).press('ArrowLeft');
  await page.getByRole('combobox', { name: 'Customer Type' }).press('ArrowLeft');
  await page.getByRole('combobox', { name: 'Customer Type' }).press('ArrowLeft');
  await page.getByRole('combobox', { name: 'Customer Type' }).fill('re');
  await page.getByRole('combobox', { name: 'Customer Type' }).press('Enter');
  await page.getByRole('combobox', { name: 'Customer Type' }).press('Tab');
  await page.getByRole('textbox', { name: 'Address Line 1' }).fill('add1');
  await page.getByRole('textbox', { name: 'Address Line 1' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Address Line 1' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Address Line 1' }).press('Tab');
  await page.getByRole('textbox', { name: 'Address Line 2' }).fill('add2');
  await page.getByRole('textbox', { name: 'Address Line 2' }).press('Tab');
  await page.getByRole('combobox', { name: 'State' }).press('Enter');
  await page.getByRole('combobox', { name: 'State' }).fill('tam');
  await page.getByRole('combobox', { name: 'State' }).press('Enter');
  await page.getByRole('combobox', { name: 'State' }).press('Tab');
  await page.getByRole('combobox', { name: 'District' }).fill('vil');
  await page.getByRole('combobox', { name: 'District' }).press('Enter');
  await page.getByRole('combobox', { name: 'District' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'Pincode' }).fill('605103');
  await page.getByRole('spinbutton', { name: 'Pincode' }).press('Tab');
  await page.getByRole('textbox', { name: 'Ref Name' }).fill('eswar');
  await page.getByRole('textbox', { name: 'Ref Name' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'Ref Phone' }).fill('9003568114');
  await page.getByRole('spinbutton', { name: 'Ref Phone' }).press('Tab');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('Enter');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowUp');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowUp');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('ArrowUp');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('Enter');
  await page.getByRole('combobox', { name: 'Delivery point' }).press('Tab');
  await page.getByRole('combobox', { name: 'Select Scheme' }).press('Enter');
  await page.getByRole('combobox', { name: 'Select Scheme' }).press('Enter');
  await page.getByRole('combobox', { name: 'Select Scheme' }).press('Tab');
  await page.getByRole('textbox', { name: 'Fund Number' }).press('Tab');
  await page.getByRole('button', { name: 'Cancel' }).press('Tab');
  await page.getByRole('button', { name: 'OK' }).press('Enter');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Yes, Create & Send WA' }).click();
  await page.getByRole('cell', { name: '9003568114' }).click();
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('.ant-table-cell.ant-table-cell-row-hover > .ant-space > div > .ant-btn').first().click();
  await page.locator('div').filter({ hasText: /^DistrictViluppuram$/ }).first().click();
  await page.getByText('Tirupattur').click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('.ant-table-cell.ant-table-cell-row-hover > .ant-space > div:nth-child(3) > .ant-btn').click();
  await page.getByText('schemename').click();
  await page.getByLabel('Assign Scheme').getByText('schemename').click();
  await page.getByRole('button', { name: 'Remove Scheme' }).click();
  await page.getByRole('button', { name: 'Yes, Remove' }).click();
  await page.locator('.ant-table-cell.ant-table-cell-row-hover > .ant-space > div:nth-child(3) > .ant-btn').click();
  await page.locator('div').filter({ hasText: 'Assign SchemeSelect scheme to' }).nth(4).click();
  await page.getByText('M-1500').click();
  await page.getByRole('button', { name: 'Assign / Update' }).click();
  await page.getByRole('button', { name: 'Yes, Assign & Send' }).click();
  await page.getByText('Assigned Schemes').click();
  await page.getByText('F2026/').click();
  await page.getByText('F2026/').click();
  await page.getByText('Dashboard').click();
  await page.getByRole('searchbox', { name: 'Enter Customer Code or ID' }).click();
  await page.getByRole('searchbox', { name: 'Enter Fund Number' }).click();
  await page.getByRole('searchbox', { name: 'Enter Fund Number' }).fill('f2026/001');
  await page.getByRole('searchbox', { name: 'Enter Fund Number' }).press('Enter');
  await page.getByRole('button', { name: 'Close' }).first().click();
  await page.getByRole('searchbox', { name: 'Enter Customer Code or ID' }).click();
  await page.getByRole('searchbox', { name: 'Enter Customer Code or ID' }).fill('cd2026/009');
  await page.getByRole('searchbox', { name: 'Enter Customer Code or ID' }).press('Enter');
  await page.getByRole('button', { name: 'Close' }).first().click();
  await page.getByRole('searchbox', { name: 'Enter Phone Number' }).click();
  await page.getByRole('searchbox', { name: 'Enter Phone Number' }).fill('9468540461');
  await page.getByRole('searchbox', { name: 'Enter Phone Number' }).press('Enter');
  await page.getByRole('searchbox', { name: 'Enter Phone Number' }).click();
  await page.getByRole('searchbox', { name: 'Enter Phone Number' }).fill('9486540461');
  await page.getByRole('searchbox', { name: 'Enter Phone Number' }).press('Enter');
  await page.getByRole('button', { name: 'Close' }).first().click();
  await page.getByText('Reports').click();
  await page.getByText('Assigned Schemes').click();
  await page.getByRole('textbox', { name: 'Fund Number (e.g. 001)' }).click();
  await page.getByRole('textbox', { name: 'Fund Number (e.g. 001)' }).fill('f2026/001');
  await page.getByRole('textbox', { name: 'Fund Number (e.g. 001)' }).press('Enter');
  await page.locator('#rc_select_25').click();
  await page.getByText('SAM256 - CD2026/009 - KOMU').click();
  await page.getByText('Payments').click();
  await page.getByRole('searchbox', { name: 'Enter Fund Number (e.g.' }).click();
  await page.getByRole('searchbox', { name: 'Enter Fund Number (e.g.' }).fill('f2026/001');
  await page.getByRole('searchbox', { name: 'Enter Fund Number (e.g.' }).press('Enter');
  await page.getByRole('cell', { name: 'Pending' }).first().click();
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.getByRole('row', { name: '1 10-10-2025 ₹1500 ₹0 -' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Record Payment' }).click();
  await page.getByRole('button', { name: 'Yes, Pay & Notify' }).click();
  await page.getByRole('row', { name: '2 10-12-2025 ₹1500 ₹0 -' }).getByRole('button').click();
  await page.getByRole('spinbutton', { name: '* Amount Received' }).click();
  await page.getByRole('spinbutton', { name: '* Amount Received' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: '* Amount Received' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: '* Amount Received' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: '* Amount Received' }).press('ArrowRight');
  await page.getByRole('spinbutton', { name: '* Amount Received' }).fill('3000');
  await page.getByRole('textbox', { name: '* Payment Date (dd-mm-yyyy)' }).click();
  await page.getByRole('cell', { name: '24' }).click();
  await page.getByRole('button', { name: 'Record Payment' }).click();
  await page.getByRole('button', { name: 'Yes, Pay & Notify' }).click();
  await page.getByText('Auction').click();
  await page.getByRole('searchbox', { name: 'e.g. 2024_12_1234' }).click();
  await page.getByRole('searchbox', { name: 'e.g. 2024_12_1234' }).fill('f2026/001');
  await page.getByRole('searchbox', { name: 'e.g. 2024_12_1234' }).press('Enter');
  await page.getByRole('button', { name: 'dollar Pay All Remaining' }).click();
  await page.getByRole('button', { name: 'Pay All & Close' }).click();
  await page.getByText('Payment SuccessfulPayment').click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Tracking Order').click();
  await page.getByRole('button', { name: '+ New Order' }).click();
  await page.getByRole('textbox', { name: 'Order Number' }).click();
  await page.getByRole('textbox', { name: 'Order Number' }).fill('25896');
  await page.locator('#Customer_ID').click();
  await page.locator('div').filter({ hasText: 'New OrderTracking / LLM' }).nth(2).click();
  await page.locator('div').filter({ hasText: /^CustomerSelect CustomerUnregistered \/ Guest Customer$/ }).first().click();
  await page.getByText('KOMU - SAM256 (9486540461)').click();
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).dblclick();
  await page.getByRole('textbox', { name: 'Order Received Date' }).click();
  await page.getByRole('cell', { name: '10' }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Payment Received Date$/ }).first().click();
  await page.getByText('23').nth(3).click();
  await page.getByRole('spinbutton', { name: 'Payment Amount' }).click();
  await page.getByRole('spinbutton', { name: 'Payment Amount' }).fill('1000');
  await page.locator('#rc_select_32').click();
  await page.getByText('sample154').click();
  await page.locator('#rc_select_33').click();
  await page.getByText('name1').nth(1).click();
  await page.getByRole('combobox', { name: 'Source' }).click();
  await page.getByTitle('Website').click();
  await page.getByRole('spinbutton', { name: 'Parcel Quantity' }).click();
  await page.getByRole('spinbutton', { name: 'Parcel Quantity' }).fill('1');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Yes, Create & Notify' }).click();
  await page.getByRole('button', { name: '+ New Order' }).click();
  await page.getByRole('textbox', { name: 'Order Number' }).click();
  await page.getByRole('textbox', { name: 'Order Number' }).fill('78945');
  await page.getByRole('checkbox', { name: 'Unregistered / Guest Customer' }).check();
  await page.getByRole('textbox', { name: 'Enter Guest / Customer Name' }).click();
  await page.getByRole('textbox', { name: 'Enter Guest / Customer Name' }).fill('nalini');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Order Received Date' }).click();
  await page.getByText('16', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Payment Received Date' }).click();
  await page.getByRole('cell', { name: '18' }).click();
  await page.getByRole('spinbutton', { name: 'Payment Amount' }).click();
  await page.getByRole('spinbutton', { name: 'Payment Amount' }).fill('89652');
  await page.getByLabel('New Order').getByText('sample154').click();
  await page.getByText('sample154').nth(2).click();
  await page.getByLabel('New Order').getByText('name1').click();
  await page.getByLabel('New Order').getByTitle('sample154').click();
  await page.getByText('sam123').nth(3).click();
  await page.getByLabel('New Order').getByTitle('sam123').click();
  await page.getByTitle('sample154').nth(1).click();
  await page.locator('div').filter({ hasText: /^name1$/ }).nth(4).click();
  await page.getByText('name1').nth(2).click();
  await page.locator('div').filter({ hasText: /^SourceSelect Source$/ }).first().click();
  await page.getByText('In Store').nth(1).click();
  await page.getByRole('spinbutton', { name: 'Parcel Quantity' }).click();
  await page.getByRole('spinbutton', { name: 'Parcel Quantity' }).fill('1');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Yes, Create & Notify' }).click();
  await page.getByText('MaDuSOFT Solutions ©').click();
  await page.getByRole('button', { name: 'delete' }).first().click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByText('Downloads').click();
  await page.getByRole('button', { name: 'eye Preview' }).click();
  await page.getByRole('tab', { name: 'Payments' }).click();
  await page.getByRole('button', { name: 'eye Preview' }).click();
  await page.getByRole('tab', { name: 'Schemes' }).click();
  await page.locator('#rc-tabs-0-panel-schemes > div > div > .ant-card-body').first().click();
  await page.getByRole('button', { name: 'eye Preview' }).click();
  await page.getByRole('tab', { name: 'Order Tracking' }).click();
  await page.getByRole('button', { name: 'eye Preview' }).click();
  await page.getByText('Tracking Order').click();
  await page.getByText('User Management').click();
  await page.getByRole('button', { name: 'user-add Create User' }).click();
  await page.getByRole('textbox', { name: '* Username' }).click();
  await page.getByRole('textbox', { name: '* Username' }).fill('komu');
  await page.getByRole('textbox', { name: '* Password' }).click();
  await page.getByRole('textbox', { name: '* Password' }).fill('komu2026');
  await page.getByRole('textbox', { name: 'Full Name' }).click();
  await page.getByRole('textbox', { name: 'Full Name' }).fill('komu');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('button', { name: 'edit Edit' }).first().click();
  await page.getByText('User', { exact: true }).click();
  await page.getByText('Admin', { exact: true }).click();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('button', { name: 'delete Delete' }).first().click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByText('Tracking Order').click();
  await page.getByText('Transport', { exact: true }).click();
  await page.getByRole('button', { name: 'delete' }).first().click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Auction').click();
  await page.getByText('Schemes', { exact: true }).click();
  await page.getByRole('menuitem', { name: 'money-collect Schemes' }).press('ArrowRight');
  await page.getByRole('menuitem', { name: 'money-collect Schemes' }).press('ArrowRight');
  await page.getByRole('menuitem', { name: 'money-collect Schemes' }).press('ArrowRight');
  await page.getByRole('menuitem', { name: 'money-collect Schemes' }).press('ArrowRight');
  await page.getByRole('menuitem', { name: 'money-collect Schemes' }).press('ArrowRight');
  await page.getByRole('menuitem', { name: 'money-collect Schemes' }).press('ArrowRight');
  await page.getByRole('menuitem', { name: 'money-collect Schemes' }).press('ArrowRight');
  await page.getByRole('button', { name: 'delete' }).first().click();
  await page.getByRole('button', { name: 'Yes, Delete It' }).click();
  await page.getByRole('cell', { name: 'test_1771168832392_560_updated' }).click();
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.getByText('Customers').click();
  await page.getByRole('menuitem', { name: 'usergroup-add Customers' }).press('ArrowRight');
  await page.getByRole('menuitem', { name: 'usergroup-add Customers' }).press('ArrowRight');
  await page.getByRole('menuitem', { name: 'usergroup-add Customers' }).press('ArrowRight');
  await page.getByRole('menuitem', { name: 'usergroup-add Customers' }).press('ArrowRight');
  await page.getByRole('menuitem', { name: 'usergroup-add Customers' }).press('ArrowRight');
  await page.getByRole('menuitem', { name: 'usergroup-add Customers' }).press('ArrowRight');
  await page.locator('.ant-table-cell.ant-table-cell-row-hover > .ant-space > div:nth-child(2) > .ant-btn').click();
  await page.getByRole('button', { name: 'Yes, Delete It' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(9) > .ant-space > div:nth-child(2) > .ant-btn').press('ArrowLeft');
  await page.locator('tr:nth-child(8) > td:nth-child(9) > .ant-space > div:nth-child(2) > .ant-btn').press('ArrowDown');
  await page.locator('.ant-table-cell.ant-table-cell-row-hover > .ant-space > div:nth-child(2) > .ant-btn').click();
  await page.getByRole('button', { name: 'Yes, Delete It' }).click();
});